// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLYcReSZxYtf4WirFV4krCZnre7NopXjw',
    appId: '1:1060546798853:web:af7fdb363d00ffa63ec36c',
    messagingSenderId: '1060546798853',
    projectId: 'movie-cinema-33822',
    authDomain: 'movie-cinema-33822.firebaseapp.com',
    storageBucket: 'movie-cinema-33822.firebasestorage.app',
    measurementId: 'G-L4NJRKRP4H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYs6VfEOyP7jUkA_t07s5kT43St0JzesM',
    appId: '1:1060546798853:android:7d14efdf566868ca3ec36c',
    messagingSenderId: '1060546798853',
    projectId: 'movie-cinema-33822',
    storageBucket: 'movie-cinema-33822.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjfFybNoxjStSmZ0pp5e94E_ApQ0xkQYY',
    appId: '1:1060546798853:ios:5b829c5a14e61cb53ec36c',
    messagingSenderId: '1060546798853',
    projectId: 'movie-cinema-33822',
    storageBucket: 'movie-cinema-33822.firebasestorage.app',
    iosBundleId: 'com.example.movieCinema',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjfFybNoxjStSmZ0pp5e94E_ApQ0xkQYY',
    appId: '1:1060546798853:ios:5b829c5a14e61cb53ec36c',
    messagingSenderId: '1060546798853',
    projectId: 'movie-cinema-33822',
    storageBucket: 'movie-cinema-33822.firebasestorage.app',
    iosBundleId: 'com.example.movieCinema',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLYcReSZxYtf4WirFV4krCZnre7NopXjw',
    appId: '1:1060546798853:web:cb915e6044707cc93ec36c',
    messagingSenderId: '1060546798853',
    projectId: 'movie-cinema-33822',
    authDomain: 'movie-cinema-33822.firebaseapp.com',
    storageBucket: 'movie-cinema-33822.firebasestorage.app',
    measurementId: 'G-PRLBVSEP2P',
  );
}
